### ISSUE TITLE
Ordering of package versions

### ISSUE THREAD

**Issue by KPostOffice** [thoth-station/python#292]
**Is your feature request related to a problem? Please describe.**
I would like to iterate through package versions from latest, descending.

**Describe the solution you'd like**
Add an optional flag to sort versions when using `source.get_package_versions(package_name)`.

**Describe alternatives you've considered**
Sorting it outside the package, however this seems like it might be a common requirement when getting package versions so it would be nice to have the feature included in this module rather than duplicating code.

**Comment by fridex** [comment]
BTW `get_package_versions` does not parse package versions but returns package-version identifier as a string. It might be a good idea to introduce another method that returns `Version` directly for this (otherwise the parsed version will be discarded and the parsing is a quite expensive task).

This might be relevant:
https://github.com/thoth-station/python/blob/fc98d1282ca1421056a3f8f52a30a7f28ee20159/thoth/python/source.py#L253-L255
